name: "Orb iOS Build"
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: "Fetch Dependencies"
        run: flutter pub get

      - name: "Set iOS Deployment Target"
        run: |
          # This command creates the iOS folder/files if they are missing
          flutter build ios --config-only
          # Now we modify the Podfile once it exists
          sed -i '' "s/platform :ios, '13.0'/platform :ios, '14.0'/g" ios/Podfile
          sed -i '' "s/# platform :ios, '13.0'/platform :ios, '14.0'/g" ios/Podfile

      - name: "Install CocoaPods"
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: "Build iOS (No Sign)"
        run: flutter build ios --release --no-codesign --deployment-target=14.0

      - name: "Create IPA Structure"
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r -y OrbApp.ipa Payload
          
      - name: "Upload the File"
        uses: actions/upload-artifact@v4
        with:
          name: Orb-iPhone-App
          path: OrbApp.ipa
