name: "Orb iOS Build"
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: "Fetch Dependencies"
        run: flutter pub get

      - name: "Prepare iOS Metadata"
        run: |
          # Create the iOS infrastructure
          flutter build ios --no-codesign --config-only
          
          # DELETE the old Podfile and write a fresh one forced to 15.0
          rm -f ios/Podfile
          cat <<PFE > ios/Podfile
          platform :ios, '15.0'
          use_frameworks!
          use_modular_headers!

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
            end
          end
          PFE

      - name: "Install CocoaPods"
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: "Build iOS (No Sign)"
        run: flutter build ios --release --no-codesign --deployment-target=15.0

      - name: "Create IPA Structure"
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r -y OrbApp.ipa Payload
          
      - name: "Upload the File"
        uses: actions/upload-artifact@v4
        with:
          name: Orb-iPhone-App
          path: OrbApp.ipa
