name: "Orb iOS Build"
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: "Build"
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
          
      - name: "Perfect Packaging"
        run: |
          mkdir -p Payload
          # This specifically copies the app into the Payload folder
          cp -r build/ios/iphoneos/Runner.app Payload/
          # This creates the zip so 'Payload' is the only thing at the top
          zip -r -y OrbApp.ipa Payload
          
      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: Orb-Final-IPA
          path: OrbApp.ipa
